# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: datanode_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'datanode_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64\x61tanode_service.proto\"3\n\x11WriteBlockRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"$\n\x12WriteBlockResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"$\n\x10ReadBlockRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\"1\n\x11ReadBlockResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0e\n\x06status\x18\x02 \x01(\t2|\n\x0f\x44\x61taNodeService\x12\x35\n\nWriteBlock\x12\x12.WriteBlockRequest\x1a\x13.WriteBlockResponse\x12\x32\n\tReadBlock\x12\x11.ReadBlockRequest\x1a\x12.ReadBlockResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'datanode_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WRITEBLOCKREQUEST']._serialized_start=26
  _globals['_WRITEBLOCKREQUEST']._serialized_end=77
  _globals['_WRITEBLOCKRESPONSE']._serialized_start=79
  _globals['_WRITEBLOCKRESPONSE']._serialized_end=115
  _globals['_READBLOCKREQUEST']._serialized_start=117
  _globals['_READBLOCKREQUEST']._serialized_end=153
  _globals['_READBLOCKRESPONSE']._serialized_start=155
  _globals['_READBLOCKRESPONSE']._serialized_end=204
  _globals['_DATANODESERVICE']._serialized_start=206
  _globals['_DATANODESERVICE']._serialized_end=330
# @@protoc_insertion_point(module_scope)
