// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: datanode_service.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteBlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockId string `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"` //identifier of the block
	Data    []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                      //binary data of the block
}

func (x *WriteBlockRequest) Reset() {
	*x = WriteBlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datanode_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBlockRequest) ProtoMessage() {}

func (x *WriteBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datanode_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBlockRequest.ProtoReflect.Descriptor instead.
func (*WriteBlockRequest) Descriptor() ([]byte, []int) {
	return file_datanode_service_proto_rawDescGZIP(), []int{0}
}

func (x *WriteBlockRequest) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *WriteBlockRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteBlockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` //status of the block storage (success or error)
}

func (x *WriteBlockResponse) Reset() {
	*x = WriteBlockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datanode_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBlockResponse) ProtoMessage() {}

func (x *WriteBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datanode_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBlockResponse.ProtoReflect.Descriptor instead.
func (*WriteBlockResponse) Descriptor() ([]byte, []int) {
	return file_datanode_service_proto_rawDescGZIP(), []int{1}
}

func (x *WriteBlockResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ReadBlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockId string `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"` //identifier of the block
}

func (x *ReadBlockRequest) Reset() {
	*x = ReadBlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datanode_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBlockRequest) ProtoMessage() {}

func (x *ReadBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datanode_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBlockRequest.ProtoReflect.Descriptor instead.
func (*ReadBlockRequest) Descriptor() ([]byte, []int) {
	return file_datanode_service_proto_rawDescGZIP(), []int{2}
}

func (x *ReadBlockRequest) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

type ReadBlockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data   []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`     //binary data of the requested block
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` //status of the operation (success or error)
}

func (x *ReadBlockResponse) Reset() {
	*x = ReadBlockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datanode_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBlockResponse) ProtoMessage() {}

func (x *ReadBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datanode_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBlockResponse.ProtoReflect.Descriptor instead.
func (*ReadBlockResponse) Descriptor() ([]byte, []int) {
	return file_datanode_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReadBlockResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadBlockResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_datanode_service_proto protoreflect.FileDescriptor

var file_datanode_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x42, 0x0a, 0x11, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2c,
	0x0a, 0x12, 0x57, 0x72, 0x69, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2d, 0x0a, 0x10,
	0x52, 0x65, 0x61, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x22, 0x3f, 0x0a, 0x11, 0x52,
	0x65, 0x61, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xc0, 0x01, 0x0a,
	0x0f, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x57, 0x0a, 0x0a, 0x57, 0x72, 0x69, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x23,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x09, 0x52, 0x65, 0x61,
	0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x22, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_datanode_service_proto_rawDescOnce sync.Once
	file_datanode_service_proto_rawDescData = file_datanode_service_proto_rawDesc
)

func file_datanode_service_proto_rawDescGZIP() []byte {
	file_datanode_service_proto_rawDescOnce.Do(func() {
		file_datanode_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_datanode_service_proto_rawDescData)
	})
	return file_datanode_service_proto_rawDescData
}

var file_datanode_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_datanode_service_proto_goTypes = []any{
	(*WriteBlockRequest)(nil),  // 0: datanode_service.WriteBlockRequest
	(*WriteBlockResponse)(nil), // 1: datanode_service.WriteBlockResponse
	(*ReadBlockRequest)(nil),   // 2: datanode_service.ReadBlockRequest
	(*ReadBlockResponse)(nil),  // 3: datanode_service.ReadBlockResponse
}
var file_datanode_service_proto_depIdxs = []int32{
	0, // 0: datanode_service.DataNodeService.WriteBlock:input_type -> datanode_service.WriteBlockRequest
	2, // 1: datanode_service.DataNodeService.ReadBlock:input_type -> datanode_service.ReadBlockRequest
	1, // 2: datanode_service.DataNodeService.WriteBlock:output_type -> datanode_service.WriteBlockResponse
	3, // 3: datanode_service.DataNodeService.ReadBlock:output_type -> datanode_service.ReadBlockResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_datanode_service_proto_init() }
func file_datanode_service_proto_init() {
	if File_datanode_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_datanode_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*WriteBlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datanode_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*WriteBlockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datanode_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ReadBlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datanode_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ReadBlockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_datanode_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datanode_service_proto_goTypes,
		DependencyIndexes: file_datanode_service_proto_depIdxs,
		MessageInfos:      file_datanode_service_proto_msgTypes,
	}.Build()
	File_datanode_service_proto = out.File
	file_datanode_service_proto_rawDesc = nil
	file_datanode_service_proto_goTypes = nil
	file_datanode_service_proto_depIdxs = nil
}
